# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20160612_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dictate', models.BooleanField(default=False)),
                ('print_it', models.BooleanField(default=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images/exams/avatars')),
                ('svg_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='images/centers/logos')),
                ('admins', models.ManyToManyField(blank=True, to='user.CenterAdminProfile')),
                ('students', models.ManyToManyField(blank=True, to='user.StudentProfile')),
                ('teachers', models.ManyToManyField(blank=True, to='user.TeacherProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('flag', models.ImageField(upload_to='images/languages/flags')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('is_question', models.BooleanField(default=True)),
                ('is_questions_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_mark', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=248)),
                ('max_time', models.IntegerField(default=30000)),
                ('recommended_time', models.IntegerField(default=30000)),
                ('welcome_message', models.TextField()),
                ('welcome_help', models.TextField(blank=True, null=True)),
                ('allowed_centers', models.ManyToManyField(to='exam.Center')),
                ('created_by_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='exam.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('print_title', models.BooleanField(default=True)),
                ('dictate_title', models.BooleanField(default=False)),
                ('introduction', models.CharField(max_length=2048)),
                ('print_introduction', models.BooleanField(default=True)),
                ('dictate_introduction', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_group_order', models.IntegerField(default=-1)),
                ('statement', models.CharField(max_length=2048)),
                ('dictate_statement', models.BooleanField(default=True)),
                ('print_statement', models.BooleanField(default=True)),
                ('statement_backup', models.CharField(blank=True, max_length=2048, null=True)),
                ('attempts_statement', models.IntegerField(blank=True, default=1, null=True)),
                ('time_to_backup', models.IntegerField(default=10)),
                ('allow_backup_buttton', models.BooleanField(default=True)),
                ('allow_backup_voice', models.BooleanField(default=False)),
                ('time_to_respond', models.IntegerField(default=10)),
                ('min_time', models.IntegerField(default=1)),
                ('attemps_response', models.IntegerField(default=1)),
                ('allow_repeat_button', models.BooleanField(default=False)),
                ('allow_repeat_voice', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Element')),
                ('post_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_answer_text', to='exam.AuxText')),
                ('post_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_statement_text', to='exam.AuxText')),
                ('pre_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_statement_text', to='exam.AuxText')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('random_select', models.BooleanField(default=False)),
                ('random_number', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Element')),
                ('questions', models.ManyToManyField(to='exam.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, default='1.1.1.1', max_length=12)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Avatar')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Call')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('js_code', models.CharField(max_length=8)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Country')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Level'),
        ),
        migrations.AddField(
            model_name='exam',
            name='responsible_teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='user.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='voices',
            field=models.ManyToManyField(to='exam.Voice'),
        ),
        migrations.AddField(
            model_name='element',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Part'),
        ),
        migrations.AddField(
            model_name='call',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='call',
            name='examinators',
            field=models.ManyToManyField(blank=True, to='user.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Voice'),
        ),
    ]
