# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20160618_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionsgroup',
            name='random_number',
        ),
        migrations.RemoveField(
            model_name='questionsgroup',
            name='random_select',
        ),
        migrations.AddField(
            model_name='element',
            name='is_groups_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionsgroup',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Element'),
        ),
        migrations.AddField(
            model_name='groupgroup',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Element'),
        ),
        migrations.AddField(
            model_name='groupgroup',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.QuestionsGroup'),
        ),
    ]
