# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20160626_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupGroup',
            new_name='GroupsGroup',
        ),
    ]
