# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20160626_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='in_group_order',
        ),
        migrations.AlterField(
            model_name='question',
            name='post_answer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='post_statement',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pre_statement',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
