# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20160626_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsgroup',
            name='groups',
        ),
        migrations.AddField(
            model_name='groupsgroup',
            name='groups',
            field=models.ManyToManyField(to='exam.QuestionsGroup'),
        ),
    ]
