# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20160626_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TopicExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expression', models.CharField(max_length=512)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_to_choose', models.IntegerField(default=10)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Element')),
                ('topics', models.ManyToManyField(to='exam.Topic')),
            ],
        ),
    ]
