# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_topic_topicexpression_topicschoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondLevelWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupsgroup',
            name='element',
        ),
        migrations.RemoveField(
            model_name='groupsgroup',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='element',
            name='is_groups_group',
        ),
        migrations.AddField(
            model_name='element',
            name='is_second_level_node',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topicschoice',
            name='time_to_choose',
            field=models.IntegerField(default=30),
        ),
        migrations.DeleteModel(
            name='GroupsGroup',
        ),
        migrations.AddField(
            model_name='secondlevelway',
            name='second_level_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Element'),
        ),
        migrations.AddField(
            model_name='element',
            name='second_level_way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.SecondLevelWay'),
        ),
    ]
