# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20160630_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondlevelway',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
