# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_secondlevelway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Part'),
        ),
    ]
