# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20160630_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='is_topic_element',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement_backup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Element'),
        ),
        migrations.AddField(
            model_name='topicelement',
            name='topics',
            field=models.ManyToManyField(to='exam.Topic'),
        ),
    ]
