# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20160706_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='js_code',
            field=models.CharField(max_length=128),
        ),
    ]
